/*
 * RIBBIT API v4
 * ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConnectApi
 */
@Disabled
public class ConnectApiTest {

    private static ConnectApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ConnectApi(apiClient);
    }

    /**
     * Bank Lookup
     *
     * Bank Lookup
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bankLookupTest() throws ApiException {
        String search = null;
        api.bankLookup()
                .search(search)
                .execute();
        // TODO: test validations
    }

    /**
     * CONNECT Session
     *
     * CONNECT Session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSessionTest() throws ApiException {
        api.createSession()
                .execute();
        // TODO: test validations
    }

    /**
     * Get Full Account Info from CONNECT Session
     *
     * Get Full Account Info from CONNECT Session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFullAccountInfoTest() throws ApiException {
        String accountToken = null;
        api.getFullAccountInfo(accountToken)
                .execute();
        // TODO: test validations
    }

}
