/*
 * RIBBIT API v4
 * ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InsightsApi
 */
@Disabled
public class InsightsApiTest {

    private static InsightsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new InsightsApi(apiClient);
    }

    /**
     * Get Insights
     *
     * Get Insights
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInsightByIdTest() throws ApiException {
        String inquiryId = null;
        api.getInsightById(inquiryId)
                .execute();
        // TODO: test validations
    }

    /**
     * BankQUALIFY
     *
     * BankQUALIFY
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void submitLoanApplicationTest() throws ApiException {
        api.submitLoanApplication()
                .execute();
        // TODO: test validations
    }

}
